new Promise((resolve, reject) => {

}).then(data => {

}).catch(err => {

})